
import { User, UserRole } from '@/types';

export const staffUsers: User[] = [
  {
    id: '1',
    name: 'SHILPA SAHU',
    email: 'shilpa.sahu@metro.com',
    role: UserRole.ENGINEER,
    badgeNo: '28463',
    aadharNo: '9696 3676 8427',
    phone: '8088114265',
    vehicleNo: 'NA',
    photoUrl: '/avatars/engineer.jpg',
    avatar: '/avatars/engineer.jpg',
    department: 'Engineering',
    joiningDate: '2022-01-01'
  },
  {
    id: '2',
    name: 'SUNIL KUMAR RAJAN',
    email: 'sunil.rajan@metro.com',
    role: UserRole.ENGINEER,
    badgeNo: '28481',
    aadharNo: '5157 5618 0505',
    phone: '9743809617',
    vehicleNo: 'WB08F9720',
    photoUrl: '/avatars/engineer.jpg',
    avatar: '/avatars/engineer.jpg',
    department: 'Engineering',
    joiningDate: '2022-01-15'
  },
  {
    id: '3',
    name: 'SHASHI SHEKHAR MISHRA',
    email: 'shashi.mishra@metro.com',
    role: UserRole.DEPOT_INCHARGE,
    badgeNo: '28529',
    aadharNo: '3273 4243 3126',
    phone: '9799494321',
    vehicleNo: 'RJ14QD3250',
    photoUrl: '/avatars/depot_incharge.jpg',
    avatar: '/avatars/depot_incharge.jpg',
    department: 'Operations',
    joiningDate: '2021-12-01'
  },
  {
    id: '4',
    name: 'ARGHYA KAR',
    email: 'arghya.kar@metro.com',
    role: UserRole.ENGINEER,
    badgeNo: '28584',
    aadharNo: '3298 7682 6260',
    phone: '9887200225',
    vehicleNo: 'NA',
    photoUrl: '/avatars/engineer.jpg',
    avatar: '/avatars/engineer.jpg',
    department: 'Engineering',
    joiningDate: '2022-02-01'
  },
  {
    id: '5',
    name: 'SHIRSHENDU MAJUMDAR',
    email: 'shirshendu.majumdar@metro.com',
    role: UserRole.ENGINEER,
    badgeNo: '28592',
    aadharNo: '7670 8754 5492',
    phone: '8882008820',
    vehicleNo: 'KA09EW7514',
    photoUrl: '/avatars/engineer.jpg',
    avatar: '/avatars/engineer.jpg',
    department: 'Engineering',
    joiningDate: '2022-02-15'
  },
  {
    id: '6',
    name: 'RITESH ANAND',
    email: 'ritesh.anand@metro.com',
    role: UserRole.ENGINEER,
    badgeNo: '29657',
    aadharNo: '4303 4619 3795',
    phone: '6289039307',
    vehicleNo: '23BH3124F',
    photoUrl: '/avatars/engineer.jpg',
    avatar: '/avatars/engineer.jpg',
    department: 'Engineering',
    joiningDate: '2022-03-01'
  },
  {
    id: '7',
    name: 'AKHILESH YADAV',
    email: 'akhilesh.yadav@metro.com',
    role: UserRole.ENGINEER,
    badgeNo: '70147',
    aadharNo: '7678 0043 0294',
    phone: '7363015472',
    vehicleNo: 'NA',
    photoUrl: '/avatars/engineer.jpg',
    avatar: '/avatars/engineer.jpg',
    department: 'Engineering',
    joiningDate: '2022-03-15'
  },
  {
    id: '8',
    name: 'CHANDAN KUMAR',
    email: 'chandan.kumar@metro.com',
    role: UserRole.ENGINEER,
    badgeNo: '70153',
    aadharNo: '5735 8890 3931',
    phone: '7827196830',
    vehicleNo: 'NA',
    photoUrl: '/avatars/engineer.jpg',
    avatar: '/avatars/engineer.jpg',
    department: 'Engineering',
    joiningDate: '2022-04-01'
  },
  {
    id: '9',
    name: 'RAHUL YADAV',
    email: 'rahul.yadav@metro.com',
    role: UserRole.ENGINEER,
    badgeNo: '70157',
    aadharNo: '3526 2708 5671',
    phone: '8250870410',
    vehicleNo: 'NA',
    photoUrl: '/avatars/engineer.jpg',
    avatar: '/avatars/engineer.jpg',
    department: 'Engineering',
    joiningDate: '2022-04-15'
  },
  {
    id: '10',
    name: 'MANIDIP BAISYA',
    email: 'manidip.baisya@metro.com',
    role: UserRole.TECHNICIAN,
    badgeNo: 'RIS/BEML/001',
    aadharNo: '4285 5282 1806',
    phone: '7003839458',
    vehicleNo: 'NA',
    photoUrl: '/avatars/technician.jpg',
    avatar: '/avatars/technician.jpg',
    department: 'Technical',
    joiningDate: '2022-05-01'
  },
  {
    id: '11',
    name: 'MD ASLAM',
    email: 'md.aslam@metro.com',
    role: UserRole.TECHNICIAN,
    badgeNo: 'RIS/BEML/002',
    aadharNo: '9409 1790 6974',
    phone: '8017550486',
    vehicleNo: 'NA',
    photoUrl: '/avatars/technician.jpg',
    avatar: '/avatars/technician.jpg',
    department: 'Technical',
    joiningDate: '2022-05-15'
  },
  {
    id: '12',
    name: 'ABOOZAR SHAIKH',
    email: 'aboozar.shaikh@metro.com',
    role: UserRole.TECHNICIAN,
    badgeNo: 'RIS/BEML/003',
    aadharNo: '2499 9698 5170',
    phone: '9007836804',
    vehicleNo: 'NA',
    photoUrl: '/avatars/technician.jpg',
    avatar: '/avatars/technician.jpg',
    department: 'Technical',
    joiningDate: '2022-06-01'
  },
  {
    id: '13',
    name: 'RAJDEEP ROY',
    email: 'rajdeep.roy@metro.com',
    role: UserRole.TECHNICIAN,
    badgeNo: 'RIS/BEML/005',
    aadharNo: '4675 3368 8407',
    phone: '8637827142',
    vehicleNo: 'NA',
    photoUrl: '/avatars/technician.jpg',
    avatar: '/avatars/technician.jpg',
    department: 'Technical',
    joiningDate: '2022-06-15'
  },
  {
    id: '14',
    name: 'SIDDHARTHA SAHA',
    email: 'siddhartha.saha@metro.com',
    role: UserRole.TECHNICIAN,
    badgeNo: 'RIS/BEML/006',
    aadharNo: '5271 1948 1475',
    phone: '9046964432',
    vehicleNo: 'NA',
    photoUrl: '/avatars/technician.jpg',
    avatar: '/avatars/technician.jpg',
    department: 'Technical',
    joiningDate: '2022-07-01'
  },
  {
    id: '15',
    name: 'CHITTARANJAN RAY CHOUDHURI',
    email: 'chittaranjan.ray@metro.com',
    role: UserRole.TECHNICIAN,
    badgeNo: 'RIS/BEML/007',
    aadharNo: '2305 1629 0407',
    phone: '9641236618',
    vehicleNo: 'NA',
    photoUrl: '/avatars/technician.jpg',
    avatar: '/avatars/technician.jpg',
    department: 'Technical',
    joiningDate: '2022-07-15'
  },
  {
    id: '17',
    name: 'HARAGOBINDA ADHIKARY',
    email: 'haragobinda.adhikary@metro.com',
    role: UserRole.TECHNICIAN,
    badgeNo: 'RIS/BEML/009',
    aadharNo: '4863 2085 0089',
    phone: '9382820621',
    vehicleNo: 'NA',
    photoUrl: '/avatars/technician.jpg',
    avatar: '/avatars/technician.jpg',
    department: 'Technical',
    joiningDate: '2022-08-01'
  },
  {
    id: '18',
    name: 'SANJAY KHARWAR',
    email: 'sanjay.kharwar@metro.com',
    role: UserRole.TECHNICIAN,
    badgeNo: 'RIS/BEML/010',
    aadharNo: '6185 2514 9450',
    phone: '7980544767',
    vehicleNo: 'NA',
    photoUrl: '/avatars/technician.jpg',
    avatar: '/avatars/technician.jpg',
    department: 'Technical',
    joiningDate: '2022-08-15'
  },
  {
    id: '19',
    name: 'KOUSHIK KUNDU',
    email: 'koushik.kundu@metro.com',
    role: UserRole.DATA_ENTRY_OPERATOR,
    badgeNo: 'RIS/BEML/011',
    aadharNo: '9659 4811 7620',
    phone: '9007120799',
    vehicleNo: 'NA',
    photoUrl: '/avatars/data_entry_operator.jpg',
    avatar: '/avatars/data_entry_operator.jpg',
    department: 'Administration',
    joiningDate: '2022-09-01'
  },
  {
    id: '21',
    name: 'MOHAMMAD ZAINUL HAQUE',
    email: 'mohammad.zainul@metro.com',
    role: UserRole.TECHNICIAN,
    badgeNo: 'RIS/BEML/012',
    aadharNo: '7758 3239 3570',
    phone: '8013236486',
    vehicleNo: 'WB02AK6274',
    photoUrl: '/avatars/technician.jpg',
    avatar: '/avatars/technician.jpg',
    department: 'Technical',
    joiningDate: '2022-09-15'
  },
  {
    id: '23',
    name: 'DEBTANU BANERJEE',
    email: 'debtanu.banerjee@metro.com',
    role: UserRole.STORE_PERSON,
    badgeNo: 'RIS/BEML/014',
    aadharNo: '4604 7620 9910',
    phone: '8910183853',
    vehicleNo: 'NA',
    photoUrl: '/avatars/store_person.jpg',
    avatar: '/avatars/store_person.jpg',
    department: 'Stores',
    joiningDate: '2022-10-01'
  },
  {
    id: '25',
    name: 'SANJAY KUMAR CHAUDHARY',
    email: 'sanjay.chaudhary@metro.com',
    role: UserRole.STORE_PERSON,
    badgeNo: 'RIS/BEML/016',
    aadharNo: '5764 7442 8367',
    phone: '7890691445',
    vehicleNo: 'NA',
    photoUrl: '/avatars/store_person.jpg',
    avatar: '/avatars/store_person.jpg',
    department: 'Stores',
    joiningDate: '2022-10-15'
  },
  {
    id: '26',
    name: 'DEEP KUMAR GHOSH',
    email: 'deep.ghosh@metro.com',
    role: UserRole.TECHNICIAN,
    badgeNo: 'RIS/BEML/017',
    aadharNo: '5813 6802 7705',
    phone: '7278387958',
    vehicleNo: 'NA',
    photoUrl: '/avatars/technician.jpg',
    avatar: '/avatars/technician.jpg',
    department: 'Technical',
    joiningDate: '2022-11-01'
  },
  {
    id: '27',
    name: 'MRITYUNJOY SARKAR',
    email: 'mrityunjoy.sarkar@metro.com',
    role: UserRole.DATA_ENTRY_OPERATOR,
    badgeNo: 'RIS/BEML/018',
    aadharNo: '5284 6996 9386',
    phone: '7074878121',
    vehicleNo: 'NA',
    photoUrl: '/avatars/data_entry_operator.jpg',
    avatar: '/avatars/data_entry_operator.jpg',
    department: 'Administration',
    joiningDate: '2022-11-15'
  },
  {
    id: '28',
    name: 'SAHIN MONDAL',
    email: 'sahin.mondal@metro.com',
    role: UserRole.STORE_PERSON,
    badgeNo: 'RIS/BEML/019',
    aadharNo: '7837 0808 4223',
    phone: '6296140186',
    vehicleNo: 'NA',
    photoUrl: '/avatars/store_person.jpg',
    avatar: '/avatars/store_person.jpg',
    department: 'Stores',
    joiningDate: '2022-12-01'
  }
];
