
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uowichbghrvtpeptdsda.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvd2ljaGJnaHJ2dHBlcHRkc2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzk3NjQsImV4cCI6MjA2MDk1NTc2NH0.0lEdCsa_QsPPDaxFeH5POyMSDZCBrJ2sM1j6kxrCWxA";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage
  }
});

// Validate connection
async function validateSupabaseConnection() {
  try {
    const { data, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error('Supabase connection issue:', error.message);
    } else {
      console.log('Supabase connection validated successfully');
    }
  } catch (err) {
    console.error('Failed to validate Supabase connection:', err);
  }
}

// Run validation in non-production environments
if (process.env.NODE_ENV !== 'production') {
  validateSupabaseConnection();
}
