// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uowichbghrvtpeptdsda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvd2ljaGJnaHJ2dHBlcHRkc2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NDU2NjQsImV4cCI6MjA1NzAyMTY2NH0.nxZMqG9POXCsaXZSCH5pbfEl_za7tQuVhom87AKcgW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);